### ISSUE TITLE
Could not find parent .git/ folder when project with some .git folders

### ISSUE THREAD

**Issue by weberdever** [jawspeak/intellij-plugin-copy-and-open-github-url#3]
Project has some folders with own .git folder. Exsample: libs/Absent/.git, libs/AbTesting/.git  projects/web/.git . When I try copy link on Stash (atlassian). Plugin throw RuntimeException

```
Could not find parent .git/ folder. Maybe path is not in a git repo? /
java.lang.RuntimeException: Could not find parent .git/ folder. Maybe path is not in a git repo? /
    at com.squareup.intellij.helper.GitRepo.findDotGitFolder(GitRepo.java:49)
    at com.squareup.intellij.helper.GitRepo.findDotGitFolder(GitRepo.java:60)
    at com.squareup.intellij.helper.GitRepo.findDotGitFolder(GitRepo.java:60)
    at com.squareup.intellij.helper.GitRepo.findDotGitFolder(GitRepo.java:60)
    at com.squareup.intellij.helper.GitRepo.<init>(GitRepo.java:27)
    at com.squareup.intellij.helper.GitRepo.<init>(GitRepo.java:22)
    at com.squareup.intellij.helper.StashRepo.<init>(StashRepo.java:11)
    at com.squareup.intellij.StashCopyAndOpenUrlForFile.actionPerformed(StashCopyAndOpenUrlForFile.java:14)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:311)
    at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:958)
    at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:281)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:109)
    at com.intellij.ui.plaf.beg.BegMenuItemUI.a(BegMenuItemUI.java:513)
    at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:45)
    at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:533)
    at java.awt.Component.processMouseEvent(Component.java:6525)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6290)
    at java.awt.Container.processEvent(Container.java:2234)
    at java.awt.Component.dispatchEventImpl(Component.java:4881)
    at java.awt.Container.dispatchEventImpl(Container.java:2292)
    at java.awt.Component.dispatchEvent(Component.java:4703)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
    at java.awt.Container.dispatchEventImpl(Container.java:2278)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4703)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:861)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:645)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by nevster** [comment]
Same issue for me
Project is in c:\ssts
Have 3 modules (java) underneath, each with own .git folder

```
Could not find parent .git/ folder. Maybe path is not in a git repo? C:\
java.lang.RuntimeException: Could not find parent .git/ folder. Maybe path is not in a git repo? C:\
at com.squareup.intellij.helper.GitRepo.findDotGitFolder(GitRepo.java:49)
at com.squareup.intellij.helper.GitRepo.findDotGitFolder(GitRepo.java:60)
at com.squareup.intellij.helper.GitRepo.<init>(GitRepo.java:27)
at com.squareup.intellij.helper.GitRepo.<init>(GitRepo.java:22)
at com.squareup.intellij.helper.StashRepo.<init>(StashRepo.java:11)
at com.squareup.intellij.StashCopyAndOpenUrlForFile.actionPerformed(StashCopyAndOpenUrlForFile.java:14)
```

**Comment by jawspeak** [comment]
Can both of you list the exact file structure, including what the root directory of your project is? Maybe a `dir` or `ls -al` or `find .` (truncated) please?

@nevster if you have 
c:\ssts\abc.git\
c:\ssts\xyz.git\
but are trying to copy the path for c:\ssts\myfile.txt, that is not under a git repo. 

Please help me reproduce this, thanks.

@weberdever - can you explain which file you are trying to open in stash?

**Comment by nevster** [comment]
```
C:\ssts>dir
Directory of C:\ssts
08/12/2015  05:09 PM    <DIR>          .idea
28/11/2015  03:37 PM    <DIR>          stms-core
17/11/2015  11:12 AM    <DIR>          another_module_etc
```

and then in stms-core

```
C:\ssts\stms-core>dir
Directory of C:\ssts\stms-core
16/10/2015  04:36 PM               176 .gitignore
16/10/2015  04:36 PM    <DIR>          .idea
01/12/2015  03:18 PM    <DIR>          Build
16/10/2015  04:36 PM    <DIR>          Main
23/11/2015  11:55 AM            32,546 stms-core.iml
```

showing hidden git directory:

```
C:\ssts\stms-core>dir /a:h
Directory of C:\ssts\stms-core
08/12/2015  05:06 PM    <DIR>          .git
```

**Comment by tripflex** [comment]
Having same problem on OSX, file is located at `/fakepath/wp-content/plugins/theplugin/includes/file.php` ... the `.git` is located at `/fakepath/wp-content/plugins/theplugin/.git`

**Comment by tripflex** [comment]
@jawspeak any luck on this at all?  Is this plugin being abandoned?  Thanks!~
